# https://hub.docker.com/_/node/

FROM node:alpine
RUN npm install -g sequelize
RUN npm install -g mysql
RUN npm install -g react-apollo
RUN npm install -g express-generator
RUN npm install -g sequelize-cli
WORKDIR /app/src